version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=${PORT:-3001}
      - DB_URL=${DB_URL}
      - DB_SERVICE_KEY=${DB_SERVICE_KEY}
    restart: unless-stopped
    env_file:
      - server/.env

