export type IconName = 
      | 'plus' 
      | 'edit' 
      | 'trash' 
      | 'bell' 
      | 'externalLink' 
      | 'userPlus' 
      | 'user' 
      | 'clock' 
      | 'arrowRight' 
      | 'arrowLeft' 
      | 'close' 
      | 'logout' 
      | 'sun' 
      | 'moon' 
      | 'checkCircle' 
      | 'xCircle' 
      | 'exclamationTriangle' 
      | 'infoCircle' 
      | 'fileText'
      | 'search'

